--
-- PostgreSQL database dump
--

-- Dumped from database version 16.14
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: rentcar_db; Type: DATABASE; Schema: -; Owner: rentcar
--

CREATE DATABASE rentcar_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE rentcar_db OWNER TO rentcar;

\connect rentcar_db

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: booking_status; Type: TYPE; Schema: public; Owner: rentcar
--

CREATE TYPE public.booking_status AS ENUM (
    'pending',
    'confirmed',
    'in_progress',
    'completed',
    'cancelled'
    );


ALTER TYPE public.booking_status OWNER TO rentcar;

--
-- Name: car_status; Type: TYPE; Schema: public; Owner: rentcar
--

CREATE TYPE public.car_status AS ENUM (
    'available',
    'rented',
    'maintenance',
    'reserved'
    );


ALTER TYPE public.car_status OWNER TO rentcar;

--
-- Name: payment_status; Type: TYPE; Schema: public; Owner: rentcar
--

CREATE TYPE public.payment_status AS ENUM (
    'pending',
    'paid',
    'failed',
    'refunded'
    );


ALTER TYPE public.payment_status OWNER TO rentcar;

--
-- Name: update_updated_at(); Type: FUNCTION; Schema: public; Owner: rentcar
--

CREATE FUNCTION public.update_updated_at() RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_updated_at() OWNER TO rentcar;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: booking_extras; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.booking_extras (
                                       id integer NOT NULL,
                                       quantity integer NOT NULL,
                                       price_per_unit numeric(10,2) NOT NULL,
                                       total_price numeric(10,2) NOT NULL,
                                       created_at timestamp(0) without time zone NOT NULL,
                                       updated_at timestamp(0) without time zone NOT NULL,
                                       booking_id integer NOT NULL,
                                       extra_service_id integer NOT NULL
);


ALTER TABLE public.booking_extras OWNER TO rentcar;

--
-- Name: booking_extras_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.booking_extras ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_extras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: booking_items; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.booking_items (
                                      id integer NOT NULL,
                                      daily_rate numeric(10,2) NOT NULL,
                                      hourly_rate numeric(10,2) DEFAULT NULL::numeric,
                                      total_price numeric(10,2) NOT NULL,
                                      created_at timestamp(0) without time zone NOT NULL,
                                      updated_at timestamp(0) without time zone NOT NULL,
                                      booking_id integer NOT NULL,
                                      car_id integer NOT NULL
);


ALTER TABLE public.booking_items OWNER TO rentcar;

--
-- Name: booking_items_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.booking_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: bookings; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.bookings (
                                 id integer NOT NULL,
                                 booking_number character varying(50) NOT NULL,
                                 pickup_date date NOT NULL,
                                 pickup_time time(0) without time zone NOT NULL,
                                 dropoff_date date NOT NULL,
                                 dropoff_time time(0) without time zone NOT NULL,
                                 total_days integer,
                                 total_hours integer,
                                 subtotal numeric(10,2) DEFAULT 0.00 NOT NULL,
                                 extras_total numeric(10,2) DEFAULT 0.00 NOT NULL,
                                 total_amount numeric(10,2) DEFAULT 0.00 NOT NULL,
                                 security_deposit numeric(10,2) DEFAULT 0.00 NOT NULL,
                                 status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
                                 notes text,
                                 created_at timestamp(0) without time zone NOT NULL,
                                 updated_at timestamp(0) without time zone NOT NULL,
                                 user_id integer NOT NULL,
                                 pickup_location_id integer NOT NULL,
                                 dropoff_location_id integer NOT NULL
);


ALTER TABLE public.bookings OWNER TO rentcar;

--
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: car_classes; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.car_classes (
                                    id integer NOT NULL,
                                    name character varying(100) NOT NULL,
                                    description text,
                                    icon character varying(50) DEFAULT NULL::character varying,
                                    daily_rate numeric(10,2) DEFAULT NULL::numeric,
                                    hourly_rate numeric(10,2) DEFAULT NULL::numeric,
                                    created_at timestamp(0) without time zone NOT NULL,
                                    updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.car_classes OWNER TO rentcar;

--
-- Name: car_classes_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.car_classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: car_extra_services; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.car_extra_services (
                                           id integer NOT NULL,
                                           price numeric(10,2) DEFAULT NULL::numeric,
                                           is_required boolean DEFAULT false NOT NULL,
                                           created_at timestamp(0) without time zone NOT NULL,
                                           updated_at timestamp(0) without time zone NOT NULL,
                                           car_id integer NOT NULL,
                                           extra_service_id integer NOT NULL
);


ALTER TABLE public.car_extra_services OWNER TO rentcar;

--
-- Name: car_extra_services_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.car_extra_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_extra_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: car_features; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.car_features (
                                     id integer NOT NULL,
                                     value character varying(100) DEFAULT NULL::character varying,
                                     created_at timestamp(0) without time zone NOT NULL,
                                     car_id integer NOT NULL,
                                     feature_id integer NOT NULL
);


ALTER TABLE public.car_features OWNER TO rentcar;

--
-- Name: car_features_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.car_features ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_features_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: car_images; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.car_images (
                                   id integer NOT NULL,
                                   image_url text NOT NULL,
                                   is_main boolean DEFAULT false NOT NULL,
                                   sort_order integer DEFAULT 0 NOT NULL,
                                   created_at timestamp(0) without time zone NOT NULL,
                                   updated_at timestamp(0) without time zone NOT NULL,
                                   car_id integer NOT NULL
);


ALTER TABLE public.car_images OWNER TO rentcar;

--
-- Name: car_images_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.car_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: car_rental_history; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.car_rental_history (
                                           id integer NOT NULL,
                                           start_mileage integer,
                                           end_mileage integer,
                                           total_distance integer,
                                           start_date timestamp(0) without time zone NOT NULL,
                                           end_date timestamp(0) without time zone NOT NULL,
                                           total_days integer,
                                           total_hours integer,
                                           condition_before character varying(50) DEFAULT NULL::character varying,
                                           condition_after character varying(50) DEFAULT NULL::character varying,
                                           notes text,
                                           created_at timestamp(0) without time zone NOT NULL,
                                           updated_at timestamp(0) without time zone NOT NULL,
                                           car_id integer NOT NULL,
                                           booking_id integer NOT NULL
);


ALTER TABLE public.car_rental_history OWNER TO rentcar;

--
-- Name: car_rental_history_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.car_rental_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_rental_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: cars; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.cars (
                             id integer NOT NULL,
                             brand character varying(100) NOT NULL,
                             model character varying(100) NOT NULL,
                             year integer NOT NULL,
                             color character varying(50) DEFAULT NULL::character varying,
                             license_plate character varying(20) NOT NULL,
                             vin character varying(20) NOT NULL,
                             mileage integer DEFAULT 0 NOT NULL,
                             fuel_type character varying(20) DEFAULT NULL::character varying,
                             transmission character varying(20) DEFAULT NULL::character varying,
                             seats integer DEFAULT 5 NOT NULL,
                             doors integer DEFAULT 4 NOT NULL,
                             bags integer DEFAULT 3 NOT NULL,
                             daily_price numeric(10,2) NOT NULL,
                             hourly_price numeric(10,2) DEFAULT NULL::numeric,
                             security_deposit numeric(10,2) DEFAULT 500.00 NOT NULL,
                             is_available boolean DEFAULT true NOT NULL,
                             status character varying(20) DEFAULT 'available'::character varying NOT NULL,
                             description text,
                             created_at timestamp(0) without time zone NOT NULL,
                             updated_at timestamp(0) without time zone NOT NULL,
                             car_class_id integer NOT NULL,
                             location_id integer NOT NULL
);


ALTER TABLE public.cars OWNER TO rentcar;

--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.doctrine_migration_versions (
                                                    version character varying(191) NOT NULL,
                                                    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
                                                    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO rentcar;

--
-- Name: extra_services; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.extra_services (
                                       id integer NOT NULL,
                                       name character varying(200) NOT NULL,
                                       description text,
                                       icon character varying(50) DEFAULT NULL::character varying,
                                       category character varying(50) DEFAULT NULL::character varying,
                                       default_price numeric(10,2) DEFAULT NULL::numeric,
                                       is_active boolean DEFAULT true NOT NULL,
                                       created_at timestamp(0) without time zone NOT NULL,
                                       updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.extra_services OWNER TO rentcar;

--
-- Name: extra_services_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.extra_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.extra_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: features; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.features (
                                 id integer NOT NULL,
                                 name character varying(100) NOT NULL,
                                 icon character varying(50) DEFAULT NULL::character varying,
                                 category character varying(50) DEFAULT NULL::character varying,
                                 created_at timestamp(0) without time zone NOT NULL,
                                 updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.features OWNER TO rentcar;

--
-- Name: features_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.features ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.features_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: locations; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.locations (
                                  id integer NOT NULL,
                                  name character varying(200) NOT NULL,
                                  address text,
                                  city character varying(100) DEFAULT NULL::character varying,
                                  state character varying(50) DEFAULT NULL::character varying,
                                  country character varying(50) DEFAULT NULL::character varying,
                                  zip_code character varying(20) DEFAULT NULL::character varying,
                                  phone character varying(20) DEFAULT NULL::character varying,
                                  email character varying(100) DEFAULT NULL::character varying,
                                  latitude numeric(10,8) DEFAULT NULL::numeric,
                                  longitude numeric(11,8) DEFAULT NULL::numeric,
                                  created_at timestamp(0) without time zone NOT NULL,
                                  updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.locations OWNER TO rentcar;

--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: password_resets; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.password_resets (
                                        id integer NOT NULL,
                                        token character varying(255) NOT NULL,
                                        expires_at timestamp(0) without time zone NOT NULL,
                                        is_used boolean NOT NULL,
                                        created_at timestamp(0) without time zone NOT NULL,
                                        updated_at timestamp(0) without time zone NOT NULL,
                                        user_id integer NOT NULL
);


ALTER TABLE public.password_resets OWNER TO rentcar;

--
-- Name: password_resets_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.password_resets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_resets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: payments; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.payments (
                                 id integer NOT NULL,
                                 amount numeric(10,2) NOT NULL,
                                 payment_method character varying(50) DEFAULT NULL::character varying,
                                 status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
                                 transaction_id character varying(100) DEFAULT NULL::character varying,
                                 payment_date timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
                                 created_at timestamp(0) without time zone NOT NULL,
                                 updated_at timestamp(0) without time zone NOT NULL,
                                 booking_id integer NOT NULL
);


ALTER TABLE public.payments OWNER TO rentcar;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.reviews (
                                id integer NOT NULL,
                                rating integer NOT NULL,
                                title character varying(255) DEFAULT NULL::character varying,
                                comment text,
                                pros text,
                                cons text,
                                is_verified boolean DEFAULT false NOT NULL,
                                helpful_count integer DEFAULT 0 NOT NULL,
                                created_at timestamp(0) without time zone NOT NULL,
                                updated_at timestamp(0) without time zone NOT NULL,
                                booking_id integer NOT NULL,
                                car_id integer NOT NULL,
                                user_id integer NOT NULL
);


ALTER TABLE public.reviews OWNER TO rentcar;

--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: users; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.users (
                              id integer NOT NULL,
                              email character varying(100) NOT NULL,
                              password_hash character varying(255) NOT NULL,
                              name character varying(100) NOT NULL,
                              phone character varying(20) DEFAULT NULL::character varying,
                              driver_license character varying(50) DEFAULT NULL::character varying,
                              passport_number character varying(50) DEFAULT NULL::character varying,
                              avatar character varying(255) DEFAULT NULL::character varying,
                              role character varying(20) DEFAULT 'customer'::character varying NOT NULL,
                              status character varying(20) DEFAULT 'active'::character varying NOT NULL,
                              created_at timestamp(0) without time zone NOT NULL,
                              updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.users OWNER TO rentcar;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Data for Name: booking_extras; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.booking_extras VALUES (14, 1, 500.00, 500.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 1, 7);
INSERT INTO public.booking_extras VALUES (15, 1, 300.00, 300.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 2, 2);
INSERT INTO public.booking_extras VALUES (16, 1, 1000.00, 1000.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 3, 7);
INSERT INTO public.booking_extras VALUES (17, 1, 500.00, 500.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 3, 10);
INSERT INTO public.booking_extras VALUES (18, 1, 400.00, 400.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 4, 5);
INSERT INTO public.booking_extras VALUES (19, 1, 600.00, 600.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 4, 6);
INSERT INTO public.booking_extras VALUES (20, 1, 200.00, 200.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 4, 4);
INSERT INTO public.booking_extras VALUES (21, 1, 1000.00, 1000.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 5, 7);
INSERT INTO public.booking_extras VALUES (22, 1, 300.00, 300.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 6, 1);
INSERT INTO public.booking_extras VALUES (23, 1, 100.00, 100.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 6, 2);
INSERT INTO public.booking_extras VALUES (24, 2, 500.00, 1000.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 7, 2);
INSERT INTO public.booking_extras VALUES (25, 1, 350.00, 350.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 7, 3);
INSERT INTO public.booking_extras VALUES (26, 1, 150.00, 150.00, '2026-07-31 13:10:51', '2026-07-31 13:10:51', 7, 12);


--
-- Data for Name: booking_items; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.booking_items VALUES (29, 3000.00, NULL, 9000.00, '2026-07-31 13:10:36', '2026-07-31 13:10:36', 1, 6);
INSERT INTO public.booking_items VALUES (30, 1700.00, NULL, 1700.00, '2026-07-31 13:10:36', '2026-07-31 13:10:36', 2, 2);
INSERT INTO public.booking_items VALUES (31, 6000.00, NULL, 12000.00, '2026-07-31 13:10:36', '2026-07-31 13:10:36', 3, 11);
INSERT INTO public.booking_items VALUES (32, 4200.00, NULL, 21000.00, '2026-07-31 13:10:36', '2026-07-31 13:10:36', 4, 8);
INSERT INTO public.booking_items VALUES (33, 8500.00, NULL, 8500.00, '2026-07-31 13:10:36', '2026-07-31 13:10:36', 5, 13);
INSERT INTO public.booking_items VALUES (34, 1500.00, NULL, 10500.00, '2026-07-31 13:10:36', '2026-07-31 13:10:36', 6, 1);
INSERT INTO public.booking_items VALUES (35, 3700.00, NULL, 11100.00, '2026-07-31 13:10:36', '2026-07-31 13:10:36', 7, 15);


--
-- Data for Name: bookings; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.bookings VALUES (6, 'BR-2026-006', '2026-07-20', '08:00:00', '2026-07-27', '08:00:00', 7, NULL, 10500.00, 400.00, 10900.00, 3000.00, 'completed', 'Отпуск в Подмосковье', '2026-07-31 13:08:54', '2026-07-31 13:08:54', 6, 3, 3);
INSERT INTO public.bookings VALUES (4, 'BR-2026-004', '2026-08-10', '12:00:00', '2026-08-15', '12:00:00', 5, NULL, 21000.00, 1200.00, 22200.00, 6000.00, 'confirmed', 'Путешествие из Казани в Сочи', '2026-07-31 13:08:54', '2026-07-31 13:08:54', 4, 5, 6);
INSERT INTO public.bookings VALUES (2, 'BR-2026-002', '2026-08-02', '09:00:00', '2026-08-03', '09:00:00', 1, NULL, 1700.00, 300.00, 2000.00, 3500.00, 'completed', 'Брала авто для поездки в аэропорт', '2026-07-31 13:08:54', '2026-07-31 13:08:54', 2, 2, 2);
INSERT INTO public.bookings VALUES (1, 'BR-2026-001', '2026-08-01', '10:00:00', '2026-08-04', '10:00:00', 3, NULL, 9000.00, 500.00, 9500.00, 5000.00, 'completed', 'Первый опыт аренды, все отлично!', '2026-07-31 13:08:54', '2026-07-31 13:08:54', 1, 1, 1);
INSERT INTO public.bookings VALUES (5, 'BR-2026-005', '2026-08-15', '11:00:00', '2026-08-16', '11:00:00', 1, NULL, 8500.00, 1000.00, 9500.00, 15000.00, 'pending', 'Юбилей, хочу шикарный автомобиль', '2026-07-31 13:08:54', '2026-07-31 13:08:54', 5, 1, 1);
INSERT INTO public.bookings VALUES (3, 'BR-2026-003', '2026-08-05', '14:00:00', '2026-08-07', '14:00:00', 2, NULL, 12000.00, 1500.00, 13500.00, 10000.00, 'in_progress', 'Деловая поездка в Санкт-Петербург', '2026-07-31 13:08:54', '2026-07-31 13:08:54', 3, 1, 4);
INSERT INTO public.bookings VALUES (7, 'BR-2026-007', '2026-07-25', '10:00:00', '2026-07-28', '10:00:00', 3, NULL, 11100.00, 1500.00, 12600.00, 7000.00, 'completed', 'Поездка с семьей на дачу', '2026-07-31 13:08:54', '2026-07-31 13:08:54', 1, 4, 4);


--
-- Data for Name: car_classes; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.car_classes VALUES (1, 'Эконом', 'Бюджетные автомобили для повседневных поездок. Идеальный выбор для города.', 'economy', 1500.00, 200.00, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.car_classes VALUES (7, 'Минивэн', 'Вместительные автомобили для больших компаний и семейных поездок.', 'minivan', 3500.00, 450.00, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.car_classes VALUES (4, 'Внедорожник (SUV)', 'Полноприводные автомобили для бездорожья и путешествий. Просторный салон.', 'suv', 4000.00, 500.00, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.car_classes VALUES (6, 'Люкс', 'Элитные автомобили представительского класса. Максимальный комфорт и статус.', 'luxury', 8000.00, 1000.00, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.car_classes VALUES (2, 'Компакт', 'Компактные автомобили с хорошей маневренностью и экономичным расходом топлива.', 'compact', 2000.00, 250.00, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.car_classes VALUES (5, 'Бизнес-класс', 'Премиальные автомобили для деловых поездок. Высокий уровень комфорта.', 'business', 5500.00, 700.00, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.car_classes VALUES (8, 'Спорткар', 'Мощные и динамичные автомобили для любителей скорости и адреналина.', 'sport', 7000.00, 900.00, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.car_classes VALUES (3, 'Средний', 'Универсальные автомобили для семьи и длительных поездок. Комфорт и надежность.', 'midsize', 2800.00, 350.00, '2026-07-31 13:02:11', '2026-07-31 13:02:11');


--
-- Data for Name: car_extra_services; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.car_extra_services VALUES (1, 300.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 1, 1);
INSERT INTO public.car_extra_services VALUES (2, 500.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 1, 2);
INSERT INTO public.car_extra_services VALUES (3, 1000.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 1, 7);
INSERT INTO public.car_extra_services VALUES (4, 300.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 2, 1);
INSERT INTO public.car_extra_services VALUES (5, 500.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 2, 2);
INSERT INTO public.car_extra_services VALUES (6, 1000.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 2, 7);
INSERT INTO public.car_extra_services VALUES (7, 300.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 3, 1);
INSERT INTO public.car_extra_services VALUES (8, 500.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 3, 2);
INSERT INTO public.car_extra_services VALUES (9, 1000.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 3, 7);
INSERT INTO public.car_extra_services VALUES (10, 400.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 8, 5);
INSERT INTO public.car_extra_services VALUES (11, 600.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 8, 6);
INSERT INTO public.car_extra_services VALUES (12, 800.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 8, 4);
INSERT INTO public.car_extra_services VALUES (13, 400.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 9, 5);
INSERT INTO public.car_extra_services VALUES (14, 600.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 9, 6);
INSERT INTO public.car_extra_services VALUES (15, 800.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 9, 4);
INSERT INTO public.car_extra_services VALUES (16, 400.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 10, 5);
INSERT INTO public.car_extra_services VALUES (17, 600.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 10, 6);
INSERT INTO public.car_extra_services VALUES (18, 800.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 10, 4);
INSERT INTO public.car_extra_services VALUES (19, 300.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 11, 1);
INSERT INTO public.car_extra_services VALUES (20, 500.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 11, 2);
INSERT INTO public.car_extra_services VALUES (21, 350.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 11, 3);
INSERT INTO public.car_extra_services VALUES (22, 1000.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 11, 7);
INSERT INTO public.car_extra_services VALUES (23, 400.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 11, 8);
INSERT INTO public.car_extra_services VALUES (24, 700.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 11, 9);
INSERT INTO public.car_extra_services VALUES (25, 2000.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 11, 10);
INSERT INTO public.car_extra_services VALUES (26, 1500.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 11, 11);
INSERT INTO public.car_extra_services VALUES (27, 3000.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 11, 12);
INSERT INTO public.car_extra_services VALUES (28, 400.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 11, 15);
INSERT INTO public.car_extra_services VALUES (29, 500.00, true, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 15, 2);
INSERT INTO public.car_extra_services VALUES (30, 350.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 15, 3);
INSERT INTO public.car_extra_services VALUES (31, 1500.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 15, 11);
INSERT INTO public.car_extra_services VALUES (32, 500.00, true, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 16, 2);
INSERT INTO public.car_extra_services VALUES (33, 350.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 16, 3);
INSERT INTO public.car_extra_services VALUES (34, 1500.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 16, 11);
INSERT INTO public.car_extra_services VALUES (35, 1000.00, true, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 17, 7);
INSERT INTO public.car_extra_services VALUES (36, 700.00, true, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 17, 9);
INSERT INTO public.car_extra_services VALUES (37, 800.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 17, 4);
INSERT INTO public.car_extra_services VALUES (38, 1000.00, true, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 18, 7);
INSERT INTO public.car_extra_services VALUES (39, 700.00, true, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 18, 9);
INSERT INTO public.car_extra_services VALUES (40, 800.00, false, '2026-07-31 13:12:36', '2026-07-31 13:12:36', 18, 4);


--
-- Data for Name: car_features; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.car_features VALUES (1, 'Есть', '2026-07-31 13:13:14', 1, 1);
INSERT INTO public.car_features VALUES (2, 'Есть', '2026-07-31 13:13:14', 1, 2);
INSERT INTO public.car_features VALUES (3, 'Есть', '2026-07-31 13:13:14', 1, 3);
INSERT INTO public.car_features VALUES (4, 'Есть', '2026-07-31 13:13:14', 1, 11);
INSERT INTO public.car_features VALUES (5, 'Есть', '2026-07-31 13:13:14', 1, 12);
INSERT INTO public.car_features VALUES (6, 'Есть', '2026-07-31 13:13:14', 1, 13);
INSERT INTO public.car_features VALUES (7, 'Есть', '2026-07-31 13:13:14', 2, 1);
INSERT INTO public.car_features VALUES (8, 'Есть', '2026-07-31 13:13:14', 2, 2);
INSERT INTO public.car_features VALUES (9, 'Есть', '2026-07-31 13:13:14', 2, 3);
INSERT INTO public.car_features VALUES (10, 'Есть', '2026-07-31 13:13:14', 2, 4);
INSERT INTO public.car_features VALUES (11, 'Есть', '2026-07-31 13:13:14', 2, 5);
INSERT INTO public.car_features VALUES (12, 'Есть', '2026-07-31 13:13:14', 2, 6);
INSERT INTO public.car_features VALUES (13, 'Есть', '2026-07-31 13:13:14', 2, 11);
INSERT INTO public.car_features VALUES (14, 'Есть', '2026-07-31 13:13:14', 2, 12);
INSERT INTO public.car_features VALUES (15, 'Есть', '2026-07-31 13:13:14', 2, 13);
INSERT INTO public.car_features VALUES (16, 'Есть', '2026-07-31 13:13:14', 3, 1);
INSERT INTO public.car_features VALUES (17, 'Есть', '2026-07-31 13:13:14', 3, 2);
INSERT INTO public.car_features VALUES (18, 'Есть', '2026-07-31 13:13:14', 3, 3);
INSERT INTO public.car_features VALUES (19, 'Есть', '2026-07-31 13:13:14', 3, 4);
INSERT INTO public.car_features VALUES (20, 'Есть', '2026-07-31 13:13:14', 3, 5);
INSERT INTO public.car_features VALUES (21, 'Есть', '2026-07-31 13:13:14', 3, 6);
INSERT INTO public.car_features VALUES (22, 'Есть', '2026-07-31 13:13:14', 3, 11);
INSERT INTO public.car_features VALUES (23, 'Есть', '2026-07-31 13:13:14', 3, 12);
INSERT INTO public.car_features VALUES (24, 'Есть', '2026-07-31 13:13:14', 3, 13);
INSERT INTO public.car_features VALUES (25, 'Есть', '2026-07-31 13:13:14', 4, 1);
INSERT INTO public.car_features VALUES (26, 'Есть', '2026-07-31 13:13:14', 4, 2);
INSERT INTO public.car_features VALUES (27, 'Есть', '2026-07-31 13:13:14', 4, 3);
INSERT INTO public.car_features VALUES (28, 'Есть', '2026-07-31 13:13:14', 4, 4);
INSERT INTO public.car_features VALUES (29, 'Есть', '2026-07-31 13:13:14', 4, 5);
INSERT INTO public.car_features VALUES (30, 'Есть', '2026-07-31 13:13:14', 4, 6);
INSERT INTO public.car_features VALUES (31, 'Есть', '2026-07-31 13:13:14', 4, 9);
INSERT INTO public.car_features VALUES (32, 'Есть', '2026-07-31 13:13:14', 4, 10);
INSERT INTO public.car_features VALUES (33, 'Есть', '2026-07-31 13:13:14', 4, 11);
INSERT INTO public.car_features VALUES (34, 'Есть', '2026-07-31 13:13:14', 4, 12);
INSERT INTO public.car_features VALUES (35, 'Есть', '2026-07-31 13:13:14', 4, 13);
INSERT INTO public.car_features VALUES (36, 'Есть', '2026-07-31 13:13:14', 5, 1);
INSERT INTO public.car_features VALUES (37, 'Есть', '2026-07-31 13:13:14', 5, 2);
INSERT INTO public.car_features VALUES (38, 'Есть', '2026-07-31 13:13:14', 5, 3);
INSERT INTO public.car_features VALUES (39, 'Есть', '2026-07-31 13:13:14', 5, 4);
INSERT INTO public.car_features VALUES (40, 'Есть', '2026-07-31 13:13:14', 5, 5);
INSERT INTO public.car_features VALUES (41, 'Есть', '2026-07-31 13:13:14', 5, 6);
INSERT INTO public.car_features VALUES (42, 'Есть', '2026-07-31 13:13:14', 5, 9);
INSERT INTO public.car_features VALUES (43, 'Есть', '2026-07-31 13:13:14', 5, 10);
INSERT INTO public.car_features VALUES (44, 'Есть', '2026-07-31 13:13:14', 5, 11);
INSERT INTO public.car_features VALUES (45, 'Есть', '2026-07-31 13:13:14', 5, 12);
INSERT INTO public.car_features VALUES (46, 'Есть', '2026-07-31 13:13:14', 5, 13);
INSERT INTO public.car_features VALUES (47, 'Есть', '2026-07-31 13:13:14', 6, 1);
INSERT INTO public.car_features VALUES (48, 'Есть', '2026-07-31 13:13:14', 6, 2);
INSERT INTO public.car_features VALUES (49, 'Есть', '2026-07-31 13:13:14', 6, 3);
INSERT INTO public.car_features VALUES (50, 'Есть', '2026-07-31 13:13:14', 6, 4);
INSERT INTO public.car_features VALUES (51, 'Есть', '2026-07-31 13:13:14', 6, 5);
INSERT INTO public.car_features VALUES (52, 'Есть', '2026-07-31 13:13:14', 6, 6);
INSERT INTO public.car_features VALUES (53, 'Есть', '2026-07-31 13:13:14', 6, 7);
INSERT INTO public.car_features VALUES (54, 'Есть', '2026-07-31 13:13:14', 6, 9);
INSERT INTO public.car_features VALUES (55, 'Есть', '2026-07-31 13:13:14', 6, 10);
INSERT INTO public.car_features VALUES (56, 'Есть', '2026-07-31 13:13:14', 6, 11);
INSERT INTO public.car_features VALUES (57, 'Есть', '2026-07-31 13:13:14', 6, 12);
INSERT INTO public.car_features VALUES (58, 'Есть', '2026-07-31 13:13:14', 6, 13);
INSERT INTO public.car_features VALUES (59, 'Есть', '2026-07-31 13:13:14', 6, 16);
INSERT INTO public.car_features VALUES (60, 'Есть', '2026-07-31 13:13:14', 6, 20);
INSERT INTO public.car_features VALUES (61, 'Есть', '2026-07-31 13:13:14', 11, 1);
INSERT INTO public.car_features VALUES (62, 'Есть', '2026-07-31 13:13:14', 11, 2);
INSERT INTO public.car_features VALUES (63, 'Есть', '2026-07-31 13:13:14', 11, 3);
INSERT INTO public.car_features VALUES (64, 'Есть', '2026-07-31 13:13:14', 11, 4);
INSERT INTO public.car_features VALUES (65, 'Есть', '2026-07-31 13:13:14', 11, 5);
INSERT INTO public.car_features VALUES (66, 'Есть', '2026-07-31 13:13:14', 11, 6);
INSERT INTO public.car_features VALUES (67, 'Есть', '2026-07-31 13:13:14', 11, 7);
INSERT INTO public.car_features VALUES (68, 'Есть', '2026-07-31 13:13:14', 11, 8);
INSERT INTO public.car_features VALUES (69, 'Есть', '2026-07-31 13:13:14', 11, 9);
INSERT INTO public.car_features VALUES (70, 'Есть', '2026-07-31 13:13:14', 11, 10);
INSERT INTO public.car_features VALUES (71, 'Есть', '2026-07-31 13:13:14', 11, 11);
INSERT INTO public.car_features VALUES (72, 'Есть', '2026-07-31 13:13:14', 11, 12);
INSERT INTO public.car_features VALUES (73, 'Есть', '2026-07-31 13:13:14', 11, 13);
INSERT INTO public.car_features VALUES (74, 'Есть', '2026-07-31 13:13:14', 11, 14);
INSERT INTO public.car_features VALUES (75, 'Есть', '2026-07-31 13:13:14', 11, 15);
INSERT INTO public.car_features VALUES (76, 'Есть', '2026-07-31 13:13:14', 11, 16);
INSERT INTO public.car_features VALUES (77, 'Есть', '2026-07-31 13:13:14', 11, 17);
INSERT INTO public.car_features VALUES (78, 'Есть', '2026-07-31 13:13:14', 11, 18);
INSERT INTO public.car_features VALUES (79, 'Есть', '2026-07-31 13:13:14', 11, 19);
INSERT INTO public.car_features VALUES (80, 'Есть', '2026-07-31 13:13:14', 11, 20);
INSERT INTO public.car_features VALUES (81, 'Есть', '2026-07-31 13:13:14', 13, 1);
INSERT INTO public.car_features VALUES (82, 'Есть', '2026-07-31 13:13:14', 13, 2);
INSERT INTO public.car_features VALUES (83, 'Есть', '2026-07-31 13:13:14', 13, 3);
INSERT INTO public.car_features VALUES (84, 'Есть', '2026-07-31 13:13:14', 13, 4);
INSERT INTO public.car_features VALUES (85, 'Есть', '2026-07-31 13:13:14', 13, 5);
INSERT INTO public.car_features VALUES (86, 'Есть', '2026-07-31 13:13:14', 13, 6);
INSERT INTO public.car_features VALUES (87, 'Есть', '2026-07-31 13:13:14', 13, 7);
INSERT INTO public.car_features VALUES (88, 'Есть', '2026-07-31 13:13:14', 13, 8);
INSERT INTO public.car_features VALUES (89, 'Есть', '2026-07-31 13:13:14', 13, 9);
INSERT INTO public.car_features VALUES (90, 'Есть', '2026-07-31 13:13:14', 13, 10);
INSERT INTO public.car_features VALUES (91, 'Есть', '2026-07-31 13:13:14', 13, 11);
INSERT INTO public.car_features VALUES (92, 'Есть', '2026-07-31 13:13:14', 13, 12);
INSERT INTO public.car_features VALUES (93, 'Есть', '2026-07-31 13:13:14', 13, 13);
INSERT INTO public.car_features VALUES (94, 'Есть', '2026-07-31 13:13:14', 13, 14);
INSERT INTO public.car_features VALUES (95, 'Есть', '2026-07-31 13:13:14', 13, 15);
INSERT INTO public.car_features VALUES (96, 'Есть', '2026-07-31 13:13:14', 13, 16);
INSERT INTO public.car_features VALUES (97, 'Есть', '2026-07-31 13:13:14', 13, 17);
INSERT INTO public.car_features VALUES (98, 'Есть', '2026-07-31 13:13:14', 13, 18);
INSERT INTO public.car_features VALUES (99, 'Есть', '2026-07-31 13:13:14', 13, 19);
INSERT INTO public.car_features VALUES (100, 'Есть', '2026-07-31 13:13:14', 13, 20);


--
-- Data for Name: car_images; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.car_images VALUES (1, 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 1);
INSERT INTO public.car_images VALUES (2, 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800', false, 2, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 1);
INSERT INTO public.car_images VALUES (3, 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 2);
INSERT INTO public.car_images VALUES (4, 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 3);
INSERT INTO public.car_images VALUES (5, 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 4);
INSERT INTO public.car_images VALUES (6, 'https://images.unsplash.com/photo-1623869675783-d0b2dd4f49e2?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 5);
INSERT INTO public.car_images VALUES (7, 'https://images.unsplash.com/photo-1622225321442-3f2a229f6bcb?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 6);
INSERT INTO public.car_images VALUES (8, 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 7);
INSERT INTO public.car_images VALUES (9, 'https://images.unsplash.com/photo-1623869675783-d0b2dd4f49e2?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 8);
INSERT INTO public.car_images VALUES (10, 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 9);
INSERT INTO public.car_images VALUES (11, 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 10);
INSERT INTO public.car_images VALUES (12, 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 11);
INSERT INTO public.car_images VALUES (13, 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 12);
INSERT INTO public.car_images VALUES (14, 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 13);
INSERT INTO public.car_images VALUES (15, 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 14);
INSERT INTO public.car_images VALUES (16, 'https://images.unsplash.com/photo-1593526492327-8a2f14eb0a3b?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 15);
INSERT INTO public.car_images VALUES (17, 'https://images.unsplash.com/photo-1593526492327-8a2f14eb0a3b?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 16);
INSERT INTO public.car_images VALUES (18, 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 17);
INSERT INTO public.car_images VALUES (19, 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800', true, 1, '2026-07-31 13:13:27', '2026-07-31 13:13:27', 18);


--
-- Data for Name: car_rental_history; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.car_rental_history VALUES (1, 45000, 45420, 420, '2026-07-20 08:00:00', '2026-07-27 08:00:00', 7, NULL, 'Отличное', 'Хорошее', 'Автомобиль вернули чистыми, без повреждений', '2026-07-31 13:13:34', '2026-07-31 13:13:34', 1, 6);
INSERT INTO public.car_rental_history VALUES (2, 22000, 22280, 280, '2026-08-01 10:00:00', '2026-08-04 10:00:00', 3, NULL, 'Отличное', 'Отличное', 'Клиент доволен автомобилем', '2026-07-31 13:13:34', '2026-07-31 13:13:34', 6, 1);
INSERT INTO public.car_rental_history VALUES (3, 32000, 32150, 150, '2026-08-02 09:00:00', '2026-08-03 09:00:00', 1, NULL, 'Отличное', 'Отличное', 'Быстрая аренда, клиент спешил в аэропорт', '2026-07-31 13:13:34', '2026-07-31 13:13:34', 2, 2);
INSERT INTO public.car_rental_history VALUES (4, 25000, 25350, 350, '2026-07-25 10:00:00', '2026-07-28 10:00:00', 3, NULL, 'Отличное', 'Хорошее', 'Минивэн использовался для поездки с семьей', '2026-07-31 13:13:34', '2026-07-31 13:13:34', 15, 7);


--
-- Data for Name: cars; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.cars VALUES (3, 'Hyundai', 'Solaris', 2022, 'Серебристый', 'Т789ЕЕ', 'KMHDN41EM12345678', 15000, 'Бензин', 'Автоматическая', 5, 4, 3, 1800.00, 230.00, 3500.00, true, 'available', 'Новый автомобиль с полным набором опций', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 1, 3);
INSERT INTO public.cars VALUES (8, 'Toyota', 'RAV4', 2022, 'Серебристый', 'Е666ЕЕ', 'JTMDREV0K12345678', 16000, 'Бензин', 'Вариатор', 5, 5, 5, 4200.00, 520.00, 6000.00, true, 'available', 'Популярный кроссовер с полным приводом', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 4, 1);
INSERT INTO public.cars VALUES (11, 'BMW', '5 Series', 2023, 'Темно-синий', 'М999ММ', 'WBAJC7C05P12345678', 5000, 'Бензин', 'Автоматическая', 5, 4, 4, 6000.00, 750.00, 10000.00, true, 'available', 'Премиальный бизнес-седан с максимальной комплектацией', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 5, 1);
INSERT INTO public.cars VALUES (17, 'Porsche', '911', 2023, 'Красный', 'С555СС', 'WP0AA2A9XPS1234567', 2000, 'Бензин', 'Автоматическая', 4, 2, 2, 7500.00, 950.00, 20000.00, true, 'available', 'Легендарный спортивный автомобиль', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 8, 1);
INSERT INTO public.cars VALUES (12, 'Mercedes-Benz', 'E-Class', 2022, 'Черный', 'Х111ХХ', 'WDDZF4KB4P12345678', 12000, 'Дизель', 'Автоматическая', 5, 4, 4, 6500.00, 800.00, 12000.00, true, 'available', 'Элегантный автомобиль с дизельным двигателем', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 5, 4);
INSERT INTO public.cars VALUES (4, 'Skoda', 'Octavia', 2021, 'Синий', 'Р222РР', 'TMBDJ61XM12345678', 28000, 'Бензин', 'Автоматическая', 5, 4, 4, 2200.00, 280.00, 4000.00, true, 'available', 'Просторный лифтбек для комфортных поездок', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 2, 1);
INSERT INTO public.cars VALUES (18, 'Chevrolet', 'Corvette', 2022, 'Желтый', 'Н777НН', '1G1YC2D4XP12345678', 5000, 'Бензин', 'Автоматическая', 2, 2, 2, 7000.00, 900.00, 18000.00, true, 'available', 'Американский спортивный автомобиль с V8 двигателем', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 8, 4);
INSERT INTO public.cars VALUES (7, 'Honda', 'Accord', 2021, 'Темно-синий', 'Н555НН', '1HGCV1F3M12345678', 30000, 'Бензин', 'Вариатор', 5, 4, 4, 2800.00, 350.00, 5000.00, true, 'available', 'Просторный и комфортный седан для дальних поездок', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 3, 4);
INSERT INTO public.cars VALUES (2, 'Kia', 'Rio', 2021, 'Серый', 'М456КК', 'KNDJN2A1E12345678', 32000, 'Бензин', 'Автоматическая', 5, 4, 3, 1700.00, 220.00, 3500.00, true, 'available', 'Современный компактный автомобиль с автоматической коробкой', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 1, 2);
INSERT INTO public.cars VALUES (15, 'Toyota', 'Sienna', 2022, 'Серебристый', 'Т222ТТ', '5TDYX3DC0P12345678', 25000, 'Бензин', 'Автоматическая', 7, 5, 5, 3700.00, 480.00, 7000.00, true, 'available', 'Просторный минивэн для всей семьи', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 7, 1);
INSERT INTO public.cars VALUES (5, 'Toyota', 'Corolla', 2022, 'Красный', 'О333ОО', 'JTDKBRFU123456789', 18000, 'Бензин', 'Вариатор', 5, 4, 4, 2400.00, 300.00, 4500.00, true, 'available', 'Надежный японский автомобиль с экономичным расходом', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 2, 4);
INSERT INTO public.cars VALUES (9, 'Hyundai', 'Tucson', 2023, 'Белый', 'А777АА', 'KMHJE0KL1P12345678', 8000, 'Дизель', 'Автоматическая', 5, 5, 5, 4500.00, 550.00, 6500.00, true, 'available', 'Новый стильный кроссовер с дизельным двигателем', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 4, 4);
INSERT INTO public.cars VALUES (1, 'Renault', 'Logan', 2020, 'Белый', 'А123ВВ', 'VF1LB1R0F12345678', 45000, 'Бензин', 'Механическая', 5, 4, 3, 1500.00, 200.00, 3000.00, true, 'available', 'Надежный и экономичный автомобиль для города', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 1, 1);
INSERT INTO public.cars VALUES (16, 'Honda', 'Odyssey', 2021, 'Темно-синий', 'У333УУ', '5FNRL5H94P12345678', 32000, 'Бензин', 'Автоматическая', 7, 5, 5, 3500.00, 450.00, 7000.00, true, 'available', 'Комфортабельный минивэн с большим багажником', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 7, 4);
INSERT INTO public.cars VALUES (14, 'BMW', '7 Series', 2022, 'Белый', 'С888СС', 'WBA7F2C0XP12345678', 8000, 'Бензин', 'Автоматическая', 5, 4, 4, 8000.00, 950.00, 15000.00, true, 'available', 'Роскошный седан с инновационными технологиями', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 6, 4);
INSERT INTO public.cars VALUES (13, 'Mercedes-Benz', 'S-Class', 2023, 'Черный', 'Р999РР', 'W1K6G7HB9P12345678', 3000, 'Бензин', 'Автоматическая', 5, 4, 4, 8500.00, 1000.00, 15000.00, true, 'available', 'Флагманский седан с высочайшим уровнем комфорта', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 6, 1);
INSERT INTO public.cars VALUES (6, 'Toyota', 'Camry', 2022, 'Черный', 'К444КК', 'JTDBEHMK123456789', 22000, 'Бензин', 'Автоматическая', 5, 4, 4, 3000.00, 380.00, 5000.00, true, 'available', 'Бизнес-седан с премиальным салоном', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 3, 1);
INSERT INTO public.cars VALUES (10, 'Kia', 'Sportage', 2022, 'Оранжевый', 'В888ВВ', 'KNDPBCAC8N12345678', 12000, 'Бензин', 'Автоматическая', 5, 5, 5, 4300.00, 530.00, 6000.00, true, 'available', 'Яркий и динамичный кроссовер', '2026-07-31 13:06:31', '2026-07-31 13:06:31', 4, 5);


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: extra_services; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.extra_services VALUES (1, 'GPS-навигатор', 'Портативный GPS-навигатор с актуальными картами России', 'gps', 'Оборудование', 300.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (2, 'Детское кресло', 'Детское автомобильное кресло для безопасности ребенка (группа 1-3)', 'child_seat', 'Оборудование', 500.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (3, 'Бустер для ребенка', 'Автомобильный бустер для детей старше 6 лет', 'booster', 'Оборудование', 350.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (4, 'Зимние шины', 'Комплект зимних шин для безопасной езды в холодное время', 'winter_tires', 'Оборудование', 800.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (5, 'Цепи противоскольжения', 'Цепи противоскольжения для поездок в горной местности', 'chains', 'Оборудование', 400.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (6, 'Багажник на крышу', 'Багажник на крышу для перевозки объемных грузов', 'roof_rack', 'Оборудование', 600.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (7, 'Страхование КАСКО+', 'Расширенная страховка с покрытием до 100% ущерба', 'insurance', 'Страхование', 1000.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (8, 'Страхование ОСАГО', 'Обязательное страхование гражданской ответственности', 'insurance', 'Страхование', 400.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (9, 'Страхование от угона', 'Дополнительная страховка от угона автомобиля', 'insurance', 'Страхование', 700.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (10, 'Аренда с водителем', 'Профессиональный водитель на время аренды', 'driver', 'Комфорт', 2000.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (11, 'Доставка автомобиля', 'Доставка автомобиля до вашего адреса', 'delivery', 'Комфорт', 1500.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (12, 'Возврат в другом городе', 'Возможность вернуть автомобиль в другом городе', 'one_way', 'Комфорт', 3000.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (13, 'Полный бак топлива', 'Автомобиль выдается с полным баком топлива', 'full_tank', 'Комфорт', 0.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (14, 'Мойка автомобиля', 'Профессиональная мойка автомобиля перед выдачей', 'car_wash', 'Комфорт', 500.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.extra_services VALUES (15, 'Wi-Fi в автомобиле', 'Мобильный Wi-Fi роутер в автомобиле', 'wifi', 'Комфорт', 400.00, true, '2026-07-31 13:02:11', '2026-07-31 13:02:11');


--
-- Data for Name: features; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.features VALUES (1, 'Bluetooth', 'bluetooth', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (2, 'USB-порт', 'usb', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (3, 'Аудиосистема', 'audio', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (4, 'Камера заднего вида', 'back_camera', 'Безопасность', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (5, 'Парктроники', 'parking_sensors', 'Безопасность', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (6, 'Климат-контроль', 'climate_control', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (7, 'Кожаный салон', 'leather_seats', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (8, 'Люк', 'sunroof', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (9, 'Навигация', 'gps', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (10, 'Круиз-контроль', 'cruise_control', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (11, 'ESP', 'esp', 'Безопасность', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (12, 'ABS', 'abs', 'Безопасность', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (13, 'Подушки безопасности', 'airbags', 'Безопасность', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (14, 'Датчик дождя', 'rain_sensor', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (15, 'Датчик света', 'light_sensor', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (16, 'Подогрев сидений', 'heated_seats', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (17, 'Подогрев руля', 'heated_steering', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (18, 'Бесключевой доступ', 'keyless_go', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (19, 'Запуск двигателя с кнопки', 'push_start', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.features VALUES (20, 'Электрорегулировка сидений', 'electric_seats', 'Комфорт', '2026-07-31 13:02:11', '2026-07-31 13:02:11');


--
-- Data for Name: locations; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.locations VALUES (1, 'Центральный офис', 'ул. Тверская, д. 15', 'Москва', 'Московская область', 'Россия', '101000', '+7 (495) 123-45-67', 'moscow@carrental.ru', 55.75580000, 37.61730000, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.locations VALUES (2, 'Аэропорт Шереметьево', 'Международный аэропорт Шереметьево, Терминал D', 'Москва', 'Московская область', 'Россия', '141400', '+7 (495) 234-56-78', 'svo@carrental.ru', 55.97260000, 37.41460000, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.locations VALUES (3, 'Аэропорт Домодедово', 'Международный аэропорт Домодедово, Привокзальная площадь', 'Москва', 'Московская область', 'Россия', '142007', '+7 (495) 345-67-89', 'dme@carrental.ru', 55.41030000, 37.90610000, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.locations VALUES (4, 'Санкт-Петербург', 'Невский проспект, д. 25', 'Санкт-Петербург', 'Ленинградская область', 'Россия', '191186', '+7 (812) 456-78-90', 'spb@carrental.ru', 59.93430000, 30.33510000, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.locations VALUES (5, 'Казань', 'ул. Баумана, д. 10', 'Казань', 'Республика Татарстан', 'Россия', '420111', '+7 (843) 567-89-01', 'kazan@carrental.ru', 55.79610000, 49.10640000, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.locations VALUES (6, 'Сочи', 'ул. Навагинская, д. 5', 'Сочи', 'Краснодарский край', 'Россия', '354000', '+7 (862) 678-90-12', 'sochi@carrental.ru', 43.60280000, 39.73420000, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.locations VALUES (7, 'Екатеринбург', 'ул. Ленина, д. 50', 'Екатеринбург', 'Свердловская область', 'Россия', '620075', '+7 (343) 789-01-23', 'ekb@carrental.ru', 56.83890000, 60.60570000, '2026-07-31 13:02:11', '2026-07-31 13:02:11');
INSERT INTO public.locations VALUES (8, 'Новосибирск', 'Красный проспект, д. 40', 'Новосибирск', 'Новосибирская область', 'Россия', '630099', '+7 (383) 890-12-34', 'nsk@carrental.ru', 55.03020000, 82.92040000, '2026-07-31 13:02:11', '2026-07-31 13:02:11');


--
-- Data for Name: password_resets; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.payments VALUES (1, 9500.00, 'credit_card', 'paid', 'TXN-2026-001-001', '2026-07-28 10:00:00', '2026-07-31 13:14:23', '2026-07-31 13:14:23', 1);
INSERT INTO public.payments VALUES (2, 2000.00, 'credit_card', 'paid', 'TXN-2026-002-001', '2026-07-29 09:30:00', '2026-07-31 13:14:23', '2026-07-31 13:14:23', 2);
INSERT INTO public.payments VALUES (3, 13500.00, 'credit_card', 'paid', 'TXN-2026-003-001', '2026-08-03 14:00:00', '2026-07-31 13:14:23', '2026-07-31 13:14:23', 3);
INSERT INTO public.payments VALUES (4, 22200.00, 'paypal', 'paid', 'TXN-2026-004-001', '2026-08-08 12:00:00', '2026-07-31 13:14:23', '2026-07-31 13:14:23', 4);
INSERT INTO public.payments VALUES (5, 9500.00, 'credit_card', 'pending', NULL, NULL, '2026-07-31 13:14:23', '2026-07-31 13:14:23', 5);
INSERT INTO public.payments VALUES (6, 10900.00, 'cash', 'paid', 'TXN-2026-006-001', '2026-07-19 08:00:00', '2026-07-31 13:14:23', '2026-07-31 13:14:23', 6);
INSERT INTO public.payments VALUES (7, 12600.00, 'credit_card', 'paid', 'TXN-2026-007-001', '2026-07-24 10:00:00', '2026-07-31 13:14:23', '2026-07-31 13:14:23', 7);


--
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.reviews VALUES (1, 5, 'Отличный автомобиль!', 'Toyota Camry превзошла все ожидания. Автомобиль в идеальном состоянии, чистый, с полным баком. Очень комфортно ездить, отличная шумоизоляция. Обязательно возьму еще раз.', 'Комфортный салон, отличная управляемость, экономичный расход топлива.', 'Немного жестковата подвеска на плохих дорогах.', true, 12, '2026-07-31 13:14:33', '2026-07-31 13:14:33', 1, 6, 1);
INSERT INTO public.reviews VALUES (2, 4, 'Хороший автомобиль для города', 'Брала Kia Rio для поездки в аэропорт. Автомобиль маневренный, легко парковаться. Все работает исправно. Единственное - маловат багажник.', 'Отличная маневренность, экономичный расход, хорошая аудиосистема.', 'Маловат багажник, шумновато на трассе.', true, 5, '2026-07-31 13:14:33', '2026-07-31 13:14:33', 2, 2, 2);
INSERT INTO public.reviews VALUES (3, 4, 'Надежный автомобиль для отпуска', 'Брал Logan на неделю для поездки по Подмосковью. Автомобиль простой, но надежный. Расход топлива порадовал. Для своей цены - отличный вариант.', 'Экономичный, простой в управлении, дешевый в обслуживании.', 'Слабоватая динамика, простой салон.', true, 8, '2026-07-31 13:14:33', '2026-07-31 13:14:33', 6, 1, 1);
INSERT INTO public.reviews VALUES (4, 5, 'Идеальный минивэн для семьи!', 'Огромное спасибо за Toyota Sienna! Поездка с тремя детьми прошла идеально. В салоне много места, все поместились с комфортом. Детские кресла установили без проблем.', 'Огромный салон, много мест для багажа, комфортные сиденья.', 'Большой расход топлива, тяжеловато парковаться в городе.', true, 15, '2026-07-31 13:14:33', '2026-07-31 13:14:33', 7, 15, 2);


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: rentcar
--

INSERT INTO public.users VALUES (1, 'ivan@mail.ru', '$2a$10$H7zPZq7WwQ1NQ4R5S6T7U8V9W0X1Y2Z3A4B5C6D7E8F9G0H1I2J3K4L5', 'Иван Петров', '+7 (916) 111-22-33', '77АА123456', '4511 123456', NULL, 'customer', 'active', '2026-07-31 13:08:33', '2026-07-31 13:08:33');
INSERT INTO public.users VALUES (2, 'maria@mail.ru', '$2a$10$H7zPZq7WwQ1NQ4R5S6T7U8V9W0X1Y2Z3A4B5C6D7E8F9G0H1I2J3K4L5', 'Мария Иванова', '+7 (903) 222-33-44', '77ББ654321', '4512 234567', NULL, 'customer', 'active', '2026-07-31 13:08:33', '2026-07-31 13:08:33');
INSERT INTO public.users VALUES (3, 'alex@mail.ru', '$2a$10$H7zPZq7WwQ1NQ4R5S6T7U8V9W0X1Y2Z3A4B5C6D7E8F9G0H1I2J3K4L5', 'Алексей Смирнов', '+7 (926) 333-44-55', '78ВВ789012', '4513 345678', NULL, 'customer', 'active', '2026-07-31 13:08:33', '2026-07-31 13:08:33');
INSERT INTO public.users VALUES (4, 'elena@mail.ru', '$2a$10$H7zPZq7WwQ1NQ4R5S6T7U8V9W0X1Y2Z3A4B5C6D7E8F9G0H1I2J3K4L5', 'Елена Козлова', '+7 (925) 444-55-66', '77ГГ345678', '4514 456789', NULL, 'customer', 'active', '2026-07-31 13:08:33', '2026-07-31 13:08:33');
INSERT INTO public.users VALUES (5, 'dmitry@mail.ru', '$2a$10$H7zPZq7WwQ1NQ4R5S6T7U8V9W0X1Y2Z3A4B5C6D7E8F9G0H1I2J3K4L5', 'Дмитрий Соколов', '+7 (915) 555-66-77', '79ДД901234', '4515 567890', NULL, 'customer', 'active', '2026-07-31 13:08:33', '2026-07-31 13:08:33');
INSERT INTO public.users VALUES (6, 'admin@carrental.ru', '$2a$10$H7zPZq7WwQ1NQ4R5S6T7U8V9W0X1Y2Z3A4B5C6D7E8F9G0H1I2J3K4L5', 'Администратор', '+7 (499) 123-45-67', NULL, NULL, NULL, 'admin', 'active', '2026-07-31 13:08:33', '2026-07-31 13:08:33');


--
-- Name: booking_extras_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.booking_extras_id_seq', 26, true);


--
-- Name: booking_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.booking_items_id_seq', 35, true);


--
-- Name: bookings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.bookings_id_seq', 21, true);


--
-- Name: car_classes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.car_classes_id_seq', 18, true);


--
-- Name: car_extra_services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.car_extra_services_id_seq', 40, true);


--
-- Name: car_features_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.car_features_id_seq', 100, true);


--
-- Name: car_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.car_images_id_seq', 19, true);


--
-- Name: car_rental_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.car_rental_history_id_seq', 4, true);


--
-- Name: cars_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.cars_id_seq', 36, true);


--
-- Name: extra_services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.extra_services_id_seq', 15, true);


--
-- Name: features_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.features_id_seq', 20, true);


--
-- Name: locations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.locations_id_seq', 8, true);


--
-- Name: password_resets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.password_resets_id_seq', 1, false);


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.payments_id_seq', 7, true);


--
-- Name: reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.reviews_id_seq', 4, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.users_id_seq', 6, true);


--
-- Name: booking_extras booking_extras_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.booking_extras
    ADD CONSTRAINT booking_extras_pkey PRIMARY KEY (id);


--
-- Name: booking_items booking_items_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.booking_items
    ADD CONSTRAINT booking_items_pkey PRIMARY KEY (id);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- Name: car_classes car_classes_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_classes
    ADD CONSTRAINT car_classes_pkey PRIMARY KEY (id);


--
-- Name: car_extra_services car_extra_services_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_extra_services
    ADD CONSTRAINT car_extra_services_pkey PRIMARY KEY (id);


--
-- Name: car_features car_features_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_features
    ADD CONSTRAINT car_features_pkey PRIMARY KEY (id);


--
-- Name: car_images car_images_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_images
    ADD CONSTRAINT car_images_pkey PRIMARY KEY (id);


--
-- Name: car_rental_history car_rental_history_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_rental_history
    ADD CONSTRAINT car_rental_history_pkey PRIMARY KEY (id);


--
-- Name: cars cars_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: extra_services extra_services_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.extra_services
    ADD CONSTRAINT extra_services_pkey PRIMARY KEY (id);


--
-- Name: features features_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.features
    ADD CONSTRAINT features_pkey PRIMARY KEY (id);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: password_resets password_resets_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT password_resets_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_30f6e91760e4b879; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_30f6e91760e4b879 ON public.car_features USING btree (feature_id);


--
-- Name: idx_30f6e917c3c6f69f; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_30f6e917c3c6f69f ON public.car_features USING btree (car_id);


--
-- Name: idx_392524843301c60; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_392524843301c60 ON public.car_rental_history USING btree (booking_id);


--
-- Name: idx_39252484c3c6f69f; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_39252484c3c6f69f ON public.car_rental_history USING btree (car_id);


--
-- Name: idx_65d29b323301c60; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_65d29b323301c60 ON public.payments USING btree (booking_id);


--
-- Name: idx_6970eb0f3301c60; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_6970eb0f3301c60 ON public.reviews USING btree (booking_id);


--
-- Name: idx_6970eb0fa76ed395; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_6970eb0fa76ed395 ON public.reviews USING btree (user_id);


--
-- Name: idx_6970eb0fc3c6f69f; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_6970eb0fc3c6f69f ON public.reviews USING btree (car_id);


--
-- Name: idx_706214f83301c60; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_706214f83301c60 ON public.booking_items USING btree (booking_id);


--
-- Name: idx_706214f8c3c6f69f; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_706214f8c3c6f69f ON public.booking_items USING btree (car_id);


--
-- Name: idx_7a853c3511cb64c5; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_7a853c3511cb64c5 ON public.bookings USING btree (dropoff_location_id);


--
-- Name: idx_7a853c35a76ed395; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_7a853c35a76ed395 ON public.bookings USING btree (user_id);


--
-- Name: idx_7a853c35c77ea60d; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_7a853c35c77ea60d ON public.bookings USING btree (pickup_location_id);


--
-- Name: idx_95c71d1464d218e; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_95c71d1464d218e ON public.cars USING btree (location_id);


--
-- Name: idx_95c71d1465363e14; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_95c71d1465363e14 ON public.cars USING btree (car_class_id);


--
-- Name: idx_9d015e2f197a306b; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_9d015e2f197a306b ON public.booking_extras USING btree (extra_service_id);


--
-- Name: idx_9d015e2f3301c60; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_9d015e2f3301c60 ON public.booking_extras USING btree (booking_id);


--
-- Name: idx_9edafea1a76ed395; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_9edafea1a76ed395 ON public.password_resets USING btree (user_id);


--
-- Name: idx_car_extra_services_unique; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX idx_car_extra_services_unique ON public.car_extra_services USING btree (car_id, extra_service_id);


--
-- Name: idx_car_features_unique; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX idx_car_features_unique ON public.car_features USING btree (car_id, feature_id);


--
-- Name: idx_f097371a197a306b; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_f097371a197a306b ON public.car_extra_services USING btree (extra_service_id);


--
-- Name: idx_f097371ac3c6f69f; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_f097371ac3c6f69f ON public.car_extra_services USING btree (car_id);


--
-- Name: idx_f8775298c3c6f69f; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_f8775298c3c6f69f ON public.car_images USING btree (car_id);


--
-- Name: idx_reviews_unique; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX idx_reviews_unique ON public.reviews USING btree (booking_id, user_id);


--
-- Name: uniq_1483a5e9e7927c74; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_1483a5e9e7927c74 ON public.users USING btree (email);


--
-- Name: uniq_7a853c352d0a24aa; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_7a853c352d0a24aa ON public.bookings USING btree (booking_number);


--
-- Name: uniq_95c71d14b1085141; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_95c71d14b1085141 ON public.cars USING btree (vin);


--
-- Name: uniq_95c71d14f5aa79d0; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_95c71d14f5aa79d0 ON public.cars USING btree (license_plate);


--
-- Name: uniq_9edafea15f37a13b; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_9edafea15f37a13b ON public.password_resets USING btree (token);


--
-- Name: car_features fk_30f6e91760e4b879; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_features
    ADD CONSTRAINT fk_30f6e91760e4b879 FOREIGN KEY (feature_id) REFERENCES public.features(id) ON DELETE CASCADE;


--
-- Name: car_features fk_30f6e917c3c6f69f; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_features
    ADD CONSTRAINT fk_30f6e917c3c6f69f FOREIGN KEY (car_id) REFERENCES public.cars(id) ON DELETE CASCADE;


--
-- Name: car_rental_history fk_392524843301c60; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_rental_history
    ADD CONSTRAINT fk_392524843301c60 FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;


--
-- Name: car_rental_history fk_39252484c3c6f69f; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_rental_history
    ADD CONSTRAINT fk_39252484c3c6f69f FOREIGN KEY (car_id) REFERENCES public.cars(id) ON DELETE CASCADE;


--
-- Name: payments fk_65d29b323301c60; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk_65d29b323301c60 FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;


--
-- Name: reviews fk_6970eb0f3301c60; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk_6970eb0f3301c60 FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;


--
-- Name: reviews fk_6970eb0fa76ed395; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk_6970eb0fa76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: reviews fk_6970eb0fc3c6f69f; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk_6970eb0fc3c6f69f FOREIGN KEY (car_id) REFERENCES public.cars(id) ON DELETE CASCADE;


--
-- Name: booking_items fk_706214f83301c60; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.booking_items
    ADD CONSTRAINT fk_706214f83301c60 FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;


--
-- Name: booking_items fk_706214f8c3c6f69f; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.booking_items
    ADD CONSTRAINT fk_706214f8c3c6f69f FOREIGN KEY (car_id) REFERENCES public.cars(id) ON DELETE CASCADE;


--
-- Name: bookings fk_7a853c3511cb64c5; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_7a853c3511cb64c5 FOREIGN KEY (dropoff_location_id) REFERENCES public.locations(id);


--
-- Name: bookings fk_7a853c35a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_7a853c35a76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: bookings fk_7a853c35c77ea60d; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_7a853c35c77ea60d FOREIGN KEY (pickup_location_id) REFERENCES public.locations(id);


--
-- Name: cars fk_95c71d1464d218e; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT fk_95c71d1464d218e FOREIGN KEY (location_id) REFERENCES public.locations(id);


--
-- Name: cars fk_95c71d1465363e14; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT fk_95c71d1465363e14 FOREIGN KEY (car_class_id) REFERENCES public.car_classes(id);


--
-- Name: booking_extras fk_9d015e2f197a306b; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.booking_extras
    ADD CONSTRAINT fk_9d015e2f197a306b FOREIGN KEY (extra_service_id) REFERENCES public.extra_services(id) ON DELETE CASCADE;


--
-- Name: booking_extras fk_9d015e2f3301c60; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.booking_extras
    ADD CONSTRAINT fk_9d015e2f3301c60 FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;


--
-- Name: password_resets fk_9edafea1a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT fk_9edafea1a76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: car_extra_services fk_f097371a197a306b; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_extra_services
    ADD CONSTRAINT fk_f097371a197a306b FOREIGN KEY (extra_service_id) REFERENCES public.extra_services(id) ON DELETE CASCADE;


--
-- Name: car_extra_services fk_f097371ac3c6f69f; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_extra_services
    ADD CONSTRAINT fk_f097371ac3c6f69f FOREIGN KEY (car_id) REFERENCES public.cars(id) ON DELETE CASCADE;


--
-- Name: car_images fk_f8775298c3c6f69f; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_images
    ADD CONSTRAINT fk_f8775298c3c6f69f FOREIGN KEY (car_id) REFERENCES public.cars(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

