--
-- PostgreSQL database dump
--

-- Dumped from database version 16.14
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: rentcar_db; Type: DATABASE; Schema: -; Owner: rentcar
--

CREATE DATABASE rentcar_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE rentcar_db OWNER TO rentcar;

\connect rentcar_db

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: booking_extras; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.booking_extras (
                                       id integer NOT NULL,
                                       quantity integer NOT NULL,
                                       price_per_unit numeric(10,2) NOT NULL,
                                       total_price numeric(10,2) NOT NULL,
                                       created_at timestamp(0) without time zone NOT NULL,
                                       updated_at timestamp(0) without time zone NOT NULL,
                                       booking_id integer NOT NULL,
                                       extra_service_id integer NOT NULL
);


ALTER TABLE public.booking_extras OWNER TO rentcar;

--
-- Name: booking_extras_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.booking_extras ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_extras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: bookings; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.bookings (
                                 id integer NOT NULL,
                                 booking_number character varying(50) NOT NULL,
                                 pickup_date date NOT NULL,
                                 pickup_time time(0) without time zone NOT NULL,
                                 dropoff_date date NOT NULL,
                                 dropoff_time time(0) without time zone NOT NULL,
                                 total_days integer,
                                 total_hours integer,
                                 subtotal numeric(10,2) DEFAULT 0.00 NOT NULL,
                                 extras_total numeric(10,2) DEFAULT 0.00 NOT NULL,
                                 total_amount numeric(10,2) DEFAULT 0.00 NOT NULL,
                                 security_deposit numeric(10,2) DEFAULT 0.00 NOT NULL,
                                 status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
                                 notes text,
                                 created_at timestamp(0) without time zone NOT NULL,
                                 updated_at timestamp(0) without time zone NOT NULL,
                                 daily_rate numeric(10,2) NOT NULL,
                                 hourly_rate numeric(10,2) DEFAULT NULL::numeric,
                                 total_price numeric(10,2) NOT NULL,
                                 user_id integer NOT NULL,
                                 pickup_location_id integer NOT NULL,
                                 dropoff_location_id integer NOT NULL,
                                 car_id integer NOT NULL
);


ALTER TABLE public.bookings OWNER TO rentcar;

--
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: car_classes; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.car_classes (
                                    id integer NOT NULL,
                                    name character varying(100) NOT NULL,
                                    description text,
                                    icon character varying(50) DEFAULT NULL::character varying,
                                    daily_rate numeric(10,2) DEFAULT NULL::numeric,
                                    hourly_rate numeric(10,2) DEFAULT NULL::numeric,
                                    created_at timestamp(0) without time zone NOT NULL,
                                    updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.car_classes OWNER TO rentcar;

--
-- Name: car_classes_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.car_classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: car_extra_services; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.car_extra_services (
                                           id integer NOT NULL,
                                           price numeric(10,2) DEFAULT NULL::numeric,
                                           is_required boolean DEFAULT false NOT NULL,
                                           created_at timestamp(0) without time zone NOT NULL,
                                           updated_at timestamp(0) without time zone NOT NULL,
                                           car_id integer NOT NULL,
                                           extra_service_id integer NOT NULL
);


ALTER TABLE public.car_extra_services OWNER TO rentcar;

--
-- Name: car_extra_services_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.car_extra_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_extra_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: car_features; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.car_features (
                                     id integer NOT NULL,
                                     value character varying(100) DEFAULT NULL::character varying,
                                     created_at timestamp(0) without time zone NOT NULL,
                                     car_id integer NOT NULL,
                                     feature_id integer NOT NULL
);


ALTER TABLE public.car_features OWNER TO rentcar;

--
-- Name: car_features_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.car_features ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_features_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: car_images; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.car_images (
                                   id integer NOT NULL,
                                   image_url text NOT NULL,
                                   is_main boolean DEFAULT false NOT NULL,
                                   sort_order integer DEFAULT 0 NOT NULL,
                                   created_at timestamp(0) without time zone NOT NULL,
                                   updated_at timestamp(0) without time zone NOT NULL,
                                   car_id integer NOT NULL
);


ALTER TABLE public.car_images OWNER TO rentcar;

--
-- Name: car_images_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.car_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: car_rental_history; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.car_rental_history (
                                           id integer NOT NULL,
                                           start_mileage integer,
                                           end_mileage integer,
                                           total_distance integer,
                                           start_date timestamp(0) without time zone NOT NULL,
                                           end_date timestamp(0) without time zone NOT NULL,
                                           total_days integer,
                                           total_hours integer,
                                           condition_before character varying(50) DEFAULT NULL::character varying,
                                           condition_after character varying(50) DEFAULT NULL::character varying,
                                           notes text,
                                           created_at timestamp(0) without time zone NOT NULL,
                                           updated_at timestamp(0) without time zone NOT NULL,
                                           car_id integer NOT NULL,
                                           booking_id integer NOT NULL
);


ALTER TABLE public.car_rental_history OWNER TO rentcar;

--
-- Name: car_rental_history_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.car_rental_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_rental_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: cars; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.cars (
                             id integer NOT NULL,
                             brand character varying(100) NOT NULL,
                             model character varying(100) NOT NULL,
                             year integer NOT NULL,
                             color character varying(50) DEFAULT NULL::character varying,
                             license_plate character varying(20) NOT NULL,
                             vin character varying(20) NOT NULL,
                             mileage integer DEFAULT 0 NOT NULL,
                             fuel_type character varying(20) DEFAULT NULL::character varying,
                             transmission character varying(20) DEFAULT NULL::character varying,
                             seats integer DEFAULT 5 NOT NULL,
                             doors integer DEFAULT 4 NOT NULL,
                             bags integer DEFAULT 3 NOT NULL,
                             daily_price numeric(10,2) NOT NULL,
                             hourly_price numeric(10,2) DEFAULT NULL::numeric,
                             security_deposit numeric(10,2) DEFAULT 500.00 NOT NULL,
                             is_available boolean DEFAULT true NOT NULL,
                             status character varying(20) DEFAULT 'available'::character varying NOT NULL,
                             description text,
                             created_at timestamp(0) without time zone NOT NULL,
                             updated_at timestamp(0) without time zone NOT NULL,
                             car_class_id integer NOT NULL,
                             location_id integer NOT NULL
);


ALTER TABLE public.cars OWNER TO rentcar;

--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: extra_services; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.extra_services (
                                       id integer NOT NULL,
                                       name character varying(200) NOT NULL,
                                       description text,
                                       icon character varying(50) DEFAULT NULL::character varying,
                                       category character varying(50) DEFAULT NULL::character varying,
                                       default_price numeric(10,2) DEFAULT NULL::numeric,
                                       is_active boolean DEFAULT true NOT NULL,
                                       created_at timestamp(0) without time zone NOT NULL,
                                       updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.extra_services OWNER TO rentcar;

--
-- Name: extra_services_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.extra_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.extra_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: features; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.features (
                                 id integer NOT NULL,
                                 name character varying(100) NOT NULL,
                                 icon character varying(50) DEFAULT NULL::character varying,
                                 category character varying(50) DEFAULT NULL::character varying,
                                 category_code character varying(50) DEFAULT NULL::character varying,
                                 created_at timestamp(0) without time zone NOT NULL,
                                 updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.features OWNER TO rentcar;

--
-- Name: features_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.features ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.features_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: locations; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.locations (
                                  id integer NOT NULL,
                                  name character varying(200) NOT NULL,
                                  address text,
                                  city character varying(100) DEFAULT NULL::character varying,
                                  state character varying(50) DEFAULT NULL::character varying,
                                  country character varying(50) DEFAULT NULL::character varying,
                                  zip_code character varying(20) DEFAULT NULL::character varying,
                                  phone character varying(20) DEFAULT NULL::character varying,
                                  email character varying(100) DEFAULT NULL::character varying,
                                  latitude numeric(10,8) DEFAULT NULL::numeric,
                                  longitude numeric(11,8) DEFAULT NULL::numeric,
                                  created_at timestamp(0) without time zone NOT NULL,
                                  updated_at timestamp(0) without time zone NOT NULL,
                                  region_id integer
);


ALTER TABLE public.locations OWNER TO rentcar;

--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: password_resets; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.password_resets (
                                        id integer NOT NULL,
                                        token character varying(255) NOT NULL,
                                        expires_at timestamp(0) without time zone NOT NULL,
                                        is_used boolean NOT NULL,
                                        created_at timestamp(0) without time zone NOT NULL,
                                        updated_at timestamp(0) without time zone NOT NULL,
                                        user_id integer NOT NULL
);


ALTER TABLE public.password_resets OWNER TO rentcar;

--
-- Name: password_resets_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.password_resets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_resets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: payments; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.payments (
                                 id integer NOT NULL,
                                 amount numeric(10,2) NOT NULL,
                                 payment_method character varying(50) DEFAULT NULL::character varying,
                                 status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
                                 transaction_id character varying(100) DEFAULT NULL::character varying,
                                 payment_date timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
                                 created_at timestamp(0) without time zone NOT NULL,
                                 updated_at timestamp(0) without time zone NOT NULL,
                                 booking_id integer NOT NULL
);


ALTER TABLE public.payments OWNER TO rentcar;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.refresh_tokens (
                                       id integer NOT NULL,
                                       token character varying(255) NOT NULL,
                                       expires_at timestamp(0) without time zone NOT NULL,
                                       created_at timestamp(0) without time zone NOT NULL,
                                       user_id integer NOT NULL
);


ALTER TABLE public.refresh_tokens OWNER TO rentcar;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: regions; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.regions (
                                id integer NOT NULL,
                                code character varying(20) NOT NULL,
                                name character varying(100) NOT NULL
);


ALTER TABLE public.regions OWNER TO rentcar;

--
-- Name: regions_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.regions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.reviews (
                                id integer NOT NULL,
                                rating integer NOT NULL,
                                title character varying(255) DEFAULT NULL::character varying,
                                comment text,
                                pros text,
                                cons text,
                                is_verified boolean DEFAULT false NOT NULL,
                                helpful_count integer DEFAULT 0 NOT NULL,
                                created_at timestamp(0) without time zone NOT NULL,
                                updated_at timestamp(0) without time zone NOT NULL,
                                booking_id integer NOT NULL,
                                car_id integer NOT NULL,
                                user_id integer NOT NULL
);


ALTER TABLE public.reviews OWNER TO rentcar;

--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: roles; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.roles (
                              id integer NOT NULL,
                              name character varying(100) NOT NULL,
                              code character varying(50) NOT NULL
);


ALTER TABLE public.roles OWNER TO rentcar;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: users; Type: TABLE; Schema: public; Owner: rentcar
--

CREATE TABLE public.users (
                              id integer NOT NULL,
                              email character varying(100) NOT NULL,
                              password_hash character varying(255) NOT NULL,
                              name character varying(100) NOT NULL,
                              phone character varying(20) DEFAULT NULL::character varying,
                              driver_license character varying(50) DEFAULT NULL::character varying,
                              passport_number character varying(50) DEFAULT NULL::character varying,
                              avatar character varying(255) DEFAULT NULL::character varying,
                              status character varying(20) DEFAULT 'active'::character varying NOT NULL,
                              created_at timestamp(0) without time zone NOT NULL,
                              updated_at timestamp(0) without time zone NOT NULL,
                              role_id integer NOT NULL
);


ALTER TABLE public.users OWNER TO rentcar;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: rentcar
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Data for Name: booking_extras; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: bookings; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: car_classes; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: car_extra_services; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: car_features; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: car_images; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: car_rental_history; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: cars; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: extra_services; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: features; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: locations; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: password_resets; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: regions; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: rentcar
--



--
-- Name: booking_extras_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.booking_extras_id_seq', 1, false);


--
-- Name: bookings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.bookings_id_seq', 1, false);


--
-- Name: car_classes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.car_classes_id_seq', 1, false);


--
-- Name: car_extra_services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.car_extra_services_id_seq', 1, false);


--
-- Name: car_features_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.car_features_id_seq', 1, false);


--
-- Name: car_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.car_images_id_seq', 1, false);


--
-- Name: car_rental_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.car_rental_history_id_seq', 1, false);


--
-- Name: cars_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.cars_id_seq', 1, false);


--
-- Name: extra_services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.extra_services_id_seq', 1, false);


--
-- Name: features_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.features_id_seq', 1, false);


--
-- Name: locations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.locations_id_seq', 1, false);


--
-- Name: password_resets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.password_resets_id_seq', 1, false);


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.payments_id_seq', 1, false);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.refresh_tokens_id_seq', 1, false);


--
-- Name: regions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.regions_id_seq', 1, false);


--
-- Name: reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.reviews_id_seq', 1, false);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.roles_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rentcar
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: booking_extras booking_extras_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.booking_extras
    ADD CONSTRAINT booking_extras_pkey PRIMARY KEY (id);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- Name: car_classes car_classes_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_classes
    ADD CONSTRAINT car_classes_pkey PRIMARY KEY (id);


--
-- Name: car_extra_services car_extra_services_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_extra_services
    ADD CONSTRAINT car_extra_services_pkey PRIMARY KEY (id);


--
-- Name: car_features car_features_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_features
    ADD CONSTRAINT car_features_pkey PRIMARY KEY (id);


--
-- Name: car_images car_images_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_images
    ADD CONSTRAINT car_images_pkey PRIMARY KEY (id);


--
-- Name: car_rental_history car_rental_history_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_rental_history
    ADD CONSTRAINT car_rental_history_pkey PRIMARY KEY (id);


--
-- Name: cars cars_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);


--
-- Name: extra_services extra_services_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.extra_services
    ADD CONSTRAINT extra_services_pkey PRIMARY KEY (id);


--
-- Name: features features_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.features
    ADD CONSTRAINT features_pkey PRIMARY KEY (id);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: password_resets password_resets_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT password_resets_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: regions regions_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT regions_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_1483a5e9d60322ac; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_1483a5e9d60322ac ON public.users USING btree (role_id);


--
-- Name: idx_17e64aba98260155; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_17e64aba98260155 ON public.locations USING btree (region_id);


--
-- Name: idx_30f6e91760e4b879; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_30f6e91760e4b879 ON public.car_features USING btree (feature_id);


--
-- Name: idx_30f6e917c3c6f69f; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_30f6e917c3c6f69f ON public.car_features USING btree (car_id);


--
-- Name: idx_392524843301c60; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_392524843301c60 ON public.car_rental_history USING btree (booking_id);


--
-- Name: idx_39252484c3c6f69f; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_39252484c3c6f69f ON public.car_rental_history USING btree (car_id);


--
-- Name: idx_65d29b323301c60; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_65d29b323301c60 ON public.payments USING btree (booking_id);


--
-- Name: idx_6970eb0f3301c60; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_6970eb0f3301c60 ON public.reviews USING btree (booking_id);


--
-- Name: idx_6970eb0fa76ed395; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_6970eb0fa76ed395 ON public.reviews USING btree (user_id);


--
-- Name: idx_6970eb0fc3c6f69f; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_6970eb0fc3c6f69f ON public.reviews USING btree (car_id);


--
-- Name: idx_7a853c3511cb64c5; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_7a853c3511cb64c5 ON public.bookings USING btree (dropoff_location_id);


--
-- Name: idx_7a853c35a76ed395; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_7a853c35a76ed395 ON public.bookings USING btree (user_id);


--
-- Name: idx_7a853c35c3c6f69f; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_7a853c35c3c6f69f ON public.bookings USING btree (car_id);


--
-- Name: idx_7a853c35c77ea60d; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_7a853c35c77ea60d ON public.bookings USING btree (pickup_location_id);


--
-- Name: idx_95c71d1464d218e; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_95c71d1464d218e ON public.cars USING btree (location_id);


--
-- Name: idx_95c71d1465363e14; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_95c71d1465363e14 ON public.cars USING btree (car_class_id);


--
-- Name: idx_9bace7e1a76ed395; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_9bace7e1a76ed395 ON public.refresh_tokens USING btree (user_id);


--
-- Name: idx_9d015e2f197a306b; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_9d015e2f197a306b ON public.booking_extras USING btree (extra_service_id);


--
-- Name: idx_9d015e2f3301c60; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_9d015e2f3301c60 ON public.booking_extras USING btree (booking_id);


--
-- Name: idx_9edafea1a76ed395; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_9edafea1a76ed395 ON public.password_resets USING btree (user_id);


--
-- Name: idx_car_extra_services_unique; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX idx_car_extra_services_unique ON public.car_extra_services USING btree (car_id, extra_service_id);


--
-- Name: idx_car_features_unique; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX idx_car_features_unique ON public.car_features USING btree (car_id, feature_id);


--
-- Name: idx_f097371a197a306b; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_f097371a197a306b ON public.car_extra_services USING btree (extra_service_id);


--
-- Name: idx_f097371ac3c6f69f; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_f097371ac3c6f69f ON public.car_extra_services USING btree (car_id);


--
-- Name: idx_f8775298c3c6f69f; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE INDEX idx_f8775298c3c6f69f ON public.car_images USING btree (car_id);


--
-- Name: idx_reviews_unique; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX idx_reviews_unique ON public.reviews USING btree (booking_id, user_id);


--
-- Name: uniq_1483a5e9e7927c74; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_1483a5e9e7927c74 ON public.users USING btree (email);


--
-- Name: uniq_7a853c352d0a24aa; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_7a853c352d0a24aa ON public.bookings USING btree (booking_number);


--
-- Name: uniq_95c71d14b1085141; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_95c71d14b1085141 ON public.cars USING btree (vin);


--
-- Name: uniq_95c71d14f5aa79d0; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_95c71d14f5aa79d0 ON public.cars USING btree (license_plate);


--
-- Name: uniq_9bace7e15f37a13b; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_9bace7e15f37a13b ON public.refresh_tokens USING btree (token);


--
-- Name: uniq_9edafea15f37a13b; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_9edafea15f37a13b ON public.password_resets USING btree (token);


--
-- Name: uniq_a26779f377153098; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_a26779f377153098 ON public.regions USING btree (code);


--
-- Name: uniq_b63e2ec777153098; Type: INDEX; Schema: public; Owner: rentcar
--

CREATE UNIQUE INDEX uniq_b63e2ec777153098 ON public.roles USING btree (code);


--
-- Name: users fk_1483a5e9d60322ac; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_1483a5e9d60322ac FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: locations fk_17e64aba98260155; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT fk_17e64aba98260155 FOREIGN KEY (region_id) REFERENCES public.regions(id) ON DELETE SET NULL;


--
-- Name: car_features fk_30f6e91760e4b879; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_features
    ADD CONSTRAINT fk_30f6e91760e4b879 FOREIGN KEY (feature_id) REFERENCES public.features(id) ON DELETE CASCADE;


--
-- Name: car_features fk_30f6e917c3c6f69f; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_features
    ADD CONSTRAINT fk_30f6e917c3c6f69f FOREIGN KEY (car_id) REFERENCES public.cars(id) ON DELETE CASCADE;


--
-- Name: car_rental_history fk_392524843301c60; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_rental_history
    ADD CONSTRAINT fk_392524843301c60 FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;


--
-- Name: car_rental_history fk_39252484c3c6f69f; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_rental_history
    ADD CONSTRAINT fk_39252484c3c6f69f FOREIGN KEY (car_id) REFERENCES public.cars(id) ON DELETE CASCADE;


--
-- Name: payments fk_65d29b323301c60; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk_65d29b323301c60 FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;


--
-- Name: reviews fk_6970eb0f3301c60; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk_6970eb0f3301c60 FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;


--
-- Name: reviews fk_6970eb0fa76ed395; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk_6970eb0fa76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: reviews fk_6970eb0fc3c6f69f; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk_6970eb0fc3c6f69f FOREIGN KEY (car_id) REFERENCES public.cars(id) ON DELETE CASCADE;


--
-- Name: bookings fk_7a853c3511cb64c5; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_7a853c3511cb64c5 FOREIGN KEY (dropoff_location_id) REFERENCES public.locations(id);


--
-- Name: bookings fk_7a853c35a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_7a853c35a76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: bookings fk_7a853c35c3c6f69f; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_7a853c35c3c6f69f FOREIGN KEY (car_id) REFERENCES public.cars(id) ON DELETE CASCADE;


--
-- Name: bookings fk_7a853c35c77ea60d; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_7a853c35c77ea60d FOREIGN KEY (pickup_location_id) REFERENCES public.locations(id);


--
-- Name: cars fk_95c71d1464d218e; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT fk_95c71d1464d218e FOREIGN KEY (location_id) REFERENCES public.locations(id);


--
-- Name: cars fk_95c71d1465363e14; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT fk_95c71d1465363e14 FOREIGN KEY (car_class_id) REFERENCES public.car_classes(id);


--
-- Name: refresh_tokens fk_9bace7e1a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk_9bace7e1a76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: booking_extras fk_9d015e2f197a306b; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.booking_extras
    ADD CONSTRAINT fk_9d015e2f197a306b FOREIGN KEY (extra_service_id) REFERENCES public.extra_services(id) ON DELETE CASCADE;


--
-- Name: booking_extras fk_9d015e2f3301c60; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.booking_extras
    ADD CONSTRAINT fk_9d015e2f3301c60 FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;


--
-- Name: password_resets fk_9edafea1a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT fk_9edafea1a76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: car_extra_services fk_f097371a197a306b; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_extra_services
    ADD CONSTRAINT fk_f097371a197a306b FOREIGN KEY (extra_service_id) REFERENCES public.extra_services(id) ON DELETE CASCADE;


--
-- Name: car_extra_services fk_f097371ac3c6f69f; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_extra_services
    ADD CONSTRAINT fk_f097371ac3c6f69f FOREIGN KEY (car_id) REFERENCES public.cars(id) ON DELETE CASCADE;


--
-- Name: car_images fk_f8775298c3c6f69f; Type: FK CONSTRAINT; Schema: public; Owner: rentcar
--

ALTER TABLE ONLY public.car_images
    ADD CONSTRAINT fk_f8775298c3c6f69f FOREIGN KEY (car_id) REFERENCES public.cars(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

